### ISSUE TITLE
Timescaledb version

### ISSUE THREAD

**Issue by GeorgeBark** [Expaso/hassos-addon-timescaledb#10]
First of all, thank you very much for the hard work, I am really loving timescaledb vs influxdb for HA.

I am a bit confused though about the versions. In this page, it says TimescaleDB 2.0.1 but then in the installation guide it points to another repo (where I opened an issue before I saw this one) where the version is 1.7.4. The latter is the one that I've got installed but I would like to upgrade to TimescaleDB 2. Can I install this add-on instead of the one in the installation guide?

Thanks!

**Comment by kirbo** [comment]
I'd also like to upgrade TimescaleDB. Actually they've recently released version 2.4.2:
https://github.com/timescale/timescaledb/releases/tag/2.4.2

Any chance this addon would also get an update, soon-ish?

**Comment by guirem** [comment]
Hi @Expaso ,
Maybe a new repo/addon to avoid any conflict to current users would make it easier for you and riskless for users.
If you make it clear in project and addon description why it's depreciated people would understand I guess.

It would also allow current users wanting to migrate data to run both docker instances (aka addon) in parallel to launch a migration script (that migration script would need to be written of course).

Hope you got over the covid thing!

**Comment by Expaso** [comment]
Hi @guirem , 

This would indeed be the best  / most stable solution. Thank you!

I will upgrade TimeScale addon first in this repo, and create a new add-on, which will be based on PostgeSQL 13.
Problem solved!

**Comment by Expaso** [comment]
Status update: I'm currently testing the new version for the addon. It will include an auto-update to PostgrteSQL 14 and Timescale 2.x.
Please have a little bit more patience, I'm working as fast as I can!

**Comment by Expaso** [comment]
Still haven't forgotten you guys!

The new add-on is finished, and I'm testing it out on different scenario's.

The hardest part is that Postgres, Timescale and pgAdmin extrentions all have different upgrade / update strategies.
Also, upgrading Postgres from 12 to 14 means that during the upgrade, I need to have both versions running at the same time!
All this (in the latest versions of Alpine) means I have to compile a lot of it by hand. What a journey! 😖.

I chose to bite the apple now, because it makes upgrading to future releases a lot easier.

Any of you like to beta-test?

**Comment by weltenwort** [comment]
Thanks for all you effort :heart: If I can run it concurrently with the old addon without any data loss I'd be happy to test.

**Comment by Expaso** [comment]
@weltenwort  Thanx!

I think that should be possible. I will build a full version, and then I can supply a local add-on file, which will pull the docker image for you.
The nastiest trick is to get a copy of your database into that add-on space.  I can help you with that., but is requires you to have full SSH access to the host, as per: https://developers.home-assistant.io/docs/operating-system/debugging/

Are you familiar with that?

**Comment by weltenwort** [comment]
Yes, I'm pretty familiar with linux containers. Sounds like you want to test an in-place upgrade? Otherwise I'd simply do a dump/restore. :shrug: Let me know if there are any test scenarios that you are particularly interested in.

**Comment by weltenwort** [comment]
I've just skimmed the HA dev docs. Looks like I should be able to just install a local working copy of the addon if I change the slug in the `config.yaml`? Can you think of anything else that I need to change to avoid a collision with the already installed one?

**Comment by weltenwort** [comment]
I see you've been busy these last few hours committing stuff and building docker images. I'll just wait for you to let me know what you'd consider the best approach for testing.

**Comment by Expaso** [comment]
Hi @weltenwort , 

Yeah I'm testing a lot of stuff out. I'm very close to a release right now.
If you want to try the DEV container (it's on aarch64 only atm, so Raspberry PI), you can simply unzip these files into your addon's folder.
You will then run a separate local addon: 

[timescaledb.zip](https://github.com/Expaso/hassos-addon-timescaledb/files/8345912/timescaledb.zip)

![image](https://user-images.githubusercontent.com/26247804/160014270-502d73c0-0b36-44e2-bb2c-49567b8036b6.png)

![image](https://user-images.githubusercontent.com/26247804/160014430-558cefcd-e17a-40f2-a319-31cbe659b63d.png)

**Comment by weltenwort** [comment]
Makes sense, I'll give it a try this weekend :+1:

**Comment by weltenwort** [comment]
Based on your installation description I've checked the following:

- fresh install
- existing install
  - timescaledb hypertables still intact
  - timescaledb compression rules still intact
  - triggers still intact
  - data still intact

I found nothing wrong with either scenario :clap: My database is pretty simple, though, so I wouldn't view it as a complex test case.

Is there anything else I can help you with?

**Comment by Expaso** [comment]
Here we go! The new release it out!

Please read the release-notes carefully, and raise an issue should you have any troubles!
