### ISSUE TITLE
WARNING:  failed to launch job 1 "Telemetry Reporter": out of background workers

### ISSUE THREAD

**Issue by poudenes** [Expaso/hassos-addon-timescaledb#13]
Hi All,

I get this error in my log:

`WARNING:  failed to launch job 1 "Telemetry Reporter": out of background workers`

What can this be?

**Comment by Expaso** [comment]
It seems to be a bug in Timescale, and looks like it's fixed in newer versions. I am currently preparing a new release (and upgrading PostgreSQL in the meantime).

See: https://github.com/timescale/timescaledb/issues/1788

**Comment by Expaso** [comment]
Fixed in new Add-on version 2.0
