### ISSUE TITLE
PostGIS Error

### ISSUE THREAD

**Issue by DavyRoswinkel** [Expaso/hassos-addon-timescaledb#15]
After updating to version: 2.0.0

I am having this issue.
( Maybe it's also the cause of not being able to create a backup in the dsmrreader anymore?)

How can I solve this issue:
```


2022-03-31 14:01:33.941 UTC [504] ERROR:  function postgis_extensions_upgrade() does not exist at character 8
2022-03-31 14:01:33.941 UTC [504] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2022-03-31 14:01:33.941 UTC [504] STATEMENT:  SELECT PostGIS_Extensions_Upgrade();
ERROR:  function postgis_extensions_upgrade() does not exist
LINE 1: SELECT PostGIS_Extensions_Upgrade();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[16:01:33] INFO: Upgrading PostGIS for database: 'dsmrreader'
2022-03-31 14:01:33.987 UTC [507] ERROR:  function postgis_extensions_upgrade() does not exist at character 8
2022-03-31 14:01:33.987 UTC [507] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2022-03-31 14:01:33.987 UTC [507] STATEMENT:  SELECT PostGIS_Extensions_Upgrade();
ERROR:  function postgis_extensions_upgrade() does not exist
LINE 1: SELECT PostGIS_Extensions_Upgrade();

HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
--------------------------------------------------------------------------------------------------------------------------
Please keep in mind I use the HA addon and am a bit of a noob in using pg Admin.

**Comment by Expaso** [comment]
The error comes from he plugin trying to upgrade the Postgis extension, while this extension is not installed in your databases.
You could use pgAdmin to install it on one of your databases.

The error is not harmfull (plugin should continue on it).

The reason your backup doesn't continue is because the version of pg_dump you are using it too old for Postgresql 14.2
Can you try upgrading it?

**Comment by DavyRoswinkel** [comment]
Sorry for my delayed reply, I thought I already replied in this thread. Seems to be somewhere else.

I didn't solve this issue yet, as I don't know how to update.

The issue with the dsmrreader is solved and everything seems to be working correctly at this moment.

So I wander if it's smart for me at this moment to update, if it's only a warning and doesn't affect working correctly.

**Comment by Expaso** [comment]
This error indeed is not fatal. It comes fom the addon trying to upgrade Postgis, should it be installed.
DSMR reader needs an update to work correctly with Timescale 2.0.

For now, I would advice to hold your update back for a while, since some users are experiencing issues, which I'm investigating right now (possibly because of the upgrade process being disrupted by queries form recorder).

However, most users upgrade just fine, so If you have a decent backup, go ahead!

**Comment by Expaso** [comment]
To streamline this process a bit, I'm closing this issue to continue on #16. They all seem related.
I will post my findings there, so it's not scattered around multiple issues.

**Comment by Expaso** [comment]
@DavyRoswinkel  Issue has been found:

Please make sure you list ALL your timescale enabled databases in your configuration before trying the upgrade:

![image](https://user-images.githubusercontent.com/26247804/162141180-5d5496d2-4d7f-4cbd-9c00-d873e320734a.png)

**Comment by DavyRoswinkel** [comment]
> @DavyRoswinkel Issue has been found:
> 
> Please make sure you list ALL your timescale enabled databases in your configuration before trying the upgrade:
> 
> ![image](https://user-images.githubusercontent.com/26247804/162141180-5d5496d2-4d7f-4cbd-9c00-d873e320734a.png)

They are in my configuration.
Already upgraded to timescaledb version: 2.0.1

Logfile keeps showing:

```
[09:29:53] INFO: Upgrading PostGIS for database: 'dsmrreader'
2022-04-07 07:29:53.109 UTC [507] ERROR:  function postgis_extensions_upgrade() does not exist at character 8
2022-04-07 07:29:53.109 UTC [507] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2022-04-07 07:29:53.109 UTC [507] STATEMENT:  SELECT PostGIS_Extensions_Upgrade();
ERROR:  function postgis_extensions_upgrade() does not exist
LINE 1: SELECT PostGIS_Extensions_Upgrade();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
Same error for every database.

The dsmrreader works, also the ability to make a backup works.

Maybe I need to restore a backup ( from last week) and making sure the databases are in the configuration...then it migrates all the info ( or am I wrong???)
