### ISSUE TITLE
pg_hba.conf

### ISSUE THREAD

**Issue by melwinek** [Expaso/hassos-addon-timescaledb#17]
How can I edit pg_hba.conf ?

**Comment by Expaso** [comment]
There are 2 ways: 

1) You use something like the portainer-addon or SSH access, and edit the file in the /data/postgres directory of the addon-container itself.

2) You patch the file using init-commands (see the configuration of the addons. pg_hba.conf is located in /data/postgres/ from the viewpoint of your script.

Did this answer your question?

**Comment by melwinek** [comment]
ok, that solves the problem
