### ISSUE TITLE
Automatic updater is broken - missing libraries

### ISSUE THREAD

**Issue by derekw023** [Expaso/hassos-addon-timescaledb#18]
Here is the relevant error segment, as the addon attempts to upgrade my databases: 
```Checking for presence of required libraries                 fatal
Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    loadable_libraries.txt
Failure, exiting
[12:04:20] ERROR: PostgreSQL could not upgrade! Please inspect any errors in the lines above!
[12:04:20] ERROR: Upgrade was not succesfull.
```

I don't know how to get that file out of the addon, but with a little direction I could dig it out

**Comment by Expaso** [comment]
Hi @derekw023 , 

Can you please check that you have all timescale-databases listed in the "timescale-enabled" section of the addon configuration?

![image](https://user-images.githubusercontent.com/26247804/162805886-d5ed3f09-68a2-440c-8eb8-65ce29c45134.png)

**Comment by derekw023** [comment]
This is my whole config: 
<img width="254" alt="image" src="https://user-images.githubusercontent.com/20305986/162971215-38eba1cb-b6cd-4e02-b540-5f1a8f65ee13.png">

I have 2 other databases I created with psql commands, but I never put them in the timescale_enabled array, so timescale extensions should not be enabled on them

**Comment by Expaso** [comment]
Hi @derekw023 , 

Yould you please try to add those to this list?
I will launch an update soon which will auto-detect this, but for now it should get you past the upgrade process.

**Comment by derekw023** [comment]
I added my other databases to that list and the update passed without issue! I'll leave it up to you to close this issue or leave it around to track for the next update. Thanks!

**Comment by cyberjunky** [comment]
This (adding dsmrreader database to timescaled_enabled) before running the updateworked for me, after searching for a solution for months... thanks!

**Comment by Expaso** [comment]
Hi @cyberjunky ! I am glad it worked!

This solution was the github issue all along  https://github.com/Expaso/hassos-addon-timescaledb/issues/16#issuecomment-1091138204

If you ever run into trouble again, you can also reach me on Discord: https://discord.gg/SSdEdbAZ
I will be glad to help you out!
