### ISSUE TITLE
LTSS error 

### ISSUE THREAD

**Issue by le-andreazevedo** [Expaso/hassos-addon-timescaledb#2]
Hi @Expaso,

Also facing this error:
```
Log Details (ERROR)
Logger: custom_components.ltss
Source: custom_components/ltss/__init__.py:167
Integration: ltss (documentation)
First occurred: 4:06:44 PM (10 occurrences)
Last logged: 4:07:12 PM

Error during connection setup: (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/share/postgresql/extension/postgis.control": No such file or directory [SQL: CREATE EXTENSION IF NOT EXISTS postgis CASCADE] (Background on this error at: http://sqlalche.me/e/e3q8) (retrying in 3 seconds)
```
 I think this occurs when this is executed:
```
con.execute(
                text("CREATE EXTENSION IF NOT EXISTS postgis CASCADE"
                ).execution_options(autocommit=True))
```

**Comment by Expaso** [comment]
Hi @le-andreazevedo, 

Thanks! Did not encouter this one, because currently ltss seems broken somehow (i get a db_url not found, while it's right there in my config).

I've put out a new release, can you try if this works for you?

**Comment by Expaso** [comment]
Should be working! 

![image](https://user-images.githubusercontent.com/26247804/82680954-54f55300-9c4d-11ea-9cc3-6f2c4b4579bb.png)

I've also suggested a fix for LTSS, but I suspect you are not affected as you did not receive that error in the first place.

**Comment by le-andreazevedo** [comment]
Yes everything seems ok

Thanks a lot!
