### ISSUE TITLE
work on ha docker version

### ISSUE THREAD

**Issue by 0neday** [Expaso/hassos-addon-timescaledb#20]
this have docker image ?
[dockerfile](https://github.com/Expaso/hassos-addon-timescaledb/blob/master/timescaledb/Dockerfile#L118 ) need cross-compile for armv8?

and it have different from timescale/timescaledb:latest-pg14 in docker hub?

**Comment by Expaso** [comment]
Hi @0neday 

What are you trying to accomplish?
The docker images are on dockerhub., but are automatically pulled by Home Assistant when needed.
Does that answer your question?
