### ISSUE TITLE
Update deleted homeassistant user in Postgres

### ISSUE THREAD

**Issue by sredfern** [Expaso/hassos-addon-timescaledb#21]
Just finished fixing this but posting this as an FYI

Home assistant was having a bunch of issues. Looking in the logs it showed that HomeAssistant was unable to connect to the DB.

Prereq's: You need [this](https://developers.home-assistant.io/docs/operating-system/debugging/) setup.

1) ssh root@{{HA_IP}} -p 22222
2) docker ps | grep -I time
3) docker exec -it {{container_id}} /bin/bash
4) psql -U postgres
5) ALTER USER postgres WITH PASSWORD '{{New password}}';
6) I then used pgadmin to recreate the HA users with the right permissions
7) Reboot and everything was working fine again

I'll be turning off automatic updates in the future for this plugin. Home this helps someone.

**Comment by BobPuts** [comment]
Just tried your option. But at point 3 I get the error:
Error response from daemon: Container * is not running. When I use the command docker container ls it shows that the conatiner is running.  Do you have any idea to solve this?

**Comment by sredfern** [comment]
Hey @BobPuts - I made a mistake in my instructions. 

You need to run the command: `docker ps | grep -I time`
That will return:
`**747076f6daf3**   husselhans/hassos-addon-timescaledb-aarch64:2.0.1               "/init"                  41 hours ago   Up 41 hours   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp`
Then step 3:
`docker exec -it **747076f6daf3** /bin/bash`

**Comment by BobPuts** [comment]
Tried this and returned nothing. After a few times it says started 1 second ago, and then return nothing. It seems timescaledb is restarting everytime after the upgrade error.

**Comment by Expaso** [comment]
This issue is marked stale and will be closed.
If the issue still persists, please respond to this ticket.
