### ISSUE TITLE
Include timescaledb toolkit

### ISSUE THREAD

**Issue by Yamakaky** [Expaso/hassos-addon-timescaledb#22]
Did you consider including the [TimescaleDB toolkit in the image](https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/) in the image? It adds a lot of SQL functions for time data. My current usecase is to add [gapfilling](https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/#gapfilling-and-interpolation) for one of my sensors, but this function requires the toolkit.

**Comment by Expaso** [comment]
Hi @Yamakaky!

Yes I am certainly trying to. the only thing holding me back is this open issue that's preventing me from buidling for aarch64:

https://github.com/timescale/timescaledb-toolkit/issues/212

I'm keeping an eye on this one, as soon we have a path forward, I will add it to the addon!

**Comment by Yamakaky** [comment]
Nice! I tried to build it myself but gave up ^^

**Comment by t-o-o-m** [comment]
There seems to be Aarch64 support since 1. septembre 🎉
https://github.com/timescale/timescaledb-toolkit/issues/382#issuecomment-1259806133

**Comment by Expaso** [comment]
Wheey! So I've been watching the wrong issue there?

Well, at least we can now implement this! Stay tuned!

**Comment by Expaso** [comment]
.. why oh why is this so hard... 
![image](https://user-images.githubusercontent.com/26247804/215892934-e2684ba5-a6d0-4ace-9d90-27204013a417.png)

**Comment by Expaso** [comment]
BOOM! Version 4.0.1 is a fact.

It was definitely not a walk in the park, but now I close this issue with pride!! 🥳
