### ISSUE TITLE
Slowly rising memory leak

### ISSUE THREAD

**Issue by PeteSSMMSS** [Expaso/hassos-addon-timescaledb#26]
Hey there, thanks for this wonderful Home Assistant addon! I just discovered that the memory usage of this addon slowly rises and  so the memory of Home Assistant too. I that normal behaviour? I cleaned up the include list of the ltss integration already, the rising is not that much anymore, but still:

![SCREENSHOT-2022-11-08 at 16-24-17](https://user-images.githubusercontent.com/54634565/200605591-e7fcac95-4fb4-459c-8dc8-3f161f2c5823.png)

**Comment by Expaso** [comment]
Can you please check if this issue still persists after the latest version of the addon? I upgraded postgres and timescale in version 2.1.0 and up.

**Comment by Expaso** [comment]
If so, please reopen the issue or create a follow-up. Thank you!
