### ISSUE TITLE
Error loading shared library libLLVM-12.so

### ISSUE THREAD

**Issue by wilei** [Expaso/hassos-addon-timescaledb#27]
Hi!

I updated the timescaledb addon to the latest version a couple of days ago, and all works quite well, except the error below appears in logs now and then. And for example, this morning, something happened, and the Home Assistants Energy view has not been updated since 4 AM.

```
2022-11-12 17:00:10.092 UTC [305] ERROR:  could not load library "/usr/lib/postgresql14/llvmjit.so": Error loading shared library libLLVM-12.so: No such file or directory (needed by /usr/lib/postgresql14/llvmjit.so)
```

Interestingly, the same query (e.g. a simple SELECT query) can fail and then execute successfully when it is run multiple times in a row.

**Comment by jakosek** [comment]
Same error for me. Energy statistics are broken, but other data, recorders history is still on place.

**Comment by mvdheenux** [comment]
Same here, is there already workaround and/or fix? 
I'm  guessing that a rollback might cause other issues...

**Comment by srkoster** [comment]
I have the same error and disabled jit for now.

Login to the database and run these commands
ALTER SYSTEM SET jit=off;
select pg_reload_conf();

**Comment by shakin89** [comment]
thanks for your tips @srkoster, i've the same issue with addon 2.1.0

**Comment by Expaso** [comment]
Hi Guys!

I saw exacly the same one time, and hitting the same query multiple times did make it disappear and the query ran fine afterwarsd.

I'm curenbtly looking into this.

**Comment by srkoster** [comment]
In my case it was the query that gathers input for the statistics table, which uses different parameters on each run. Ill enable jit later today to see if the error still occurs.

**Comment by Expaso** [comment]
The problem seems to be a missing package in alpine.

Could you to add this to your config (as a workaround): 

![image](https://user-images.githubusercontent.com/26247804/201517075-faf9742f-fbfa-441d-8e60-0aa81720d2e7.png)

`apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/3.16/community/ -u llvm12-libs`

This should install the missing package at startup.
In the meantime, I will add this package to the addon at build-time, so this workaround can be removed after v2.1.1.
You should be able to enable JIT again with this workaround in place.

Does this make the error disappear for you guys?

**Comment by mvdheenux** [comment]
Hi @Expaso . 

Thanks for looking into this so quickly. 
The workaround you mentioned does seem to work for me! My energy dashboard is working again & the container logs aren't flooded with error messages anymore.

**Comment by shakin89** [comment]
Hi @Expaso,
thanks for your support. I've manually added the package in the container and the problem has disappeared.
I was running this simple query

```sql
select count(1) as cnt, entity_id 
from states
group by entity_id
order by cnt desc;
```

Installing the missing package seems to solve the problem

**Comment by Expaso** [comment]
Sweet! The new build is running.

The new version will be released soon afterwards.

**Comment by Expaso** [comment]
v2.1.1 is out, and should fix the issue.

Thanks for reporting! 🙏🏻
