### ISSUE TITLE
NOOb - how to connect in ha-OS version

### ISSUE THREAD

**Issue by eMerzh** [Expaso/hassos-addon-timescaledb#28]
Hello, 
sorry if it sounds dumb, but I homeassistant as OS on my raspberry,

i've install the extension:
i've started it , the log seems to be okay, like
>[17:56:43] INFO: done
>[17:56:43] NOTICE: TimescaleDb is running!

but then i don't know how to connect, 

from external machine the port doesn't seems to be open (by default i guess)
but if i try to psql in the ssh extension i get 
>command not found

not sure how and where i'm supposed to use it 🤔 
(after that i would like to make a duplicate of recorder for more long term & fine-grained stats)

**Comment by Expaso** [comment]
No problem! I'm glad to help you.

please check out  https://github.com/Expaso/hassos-addons/issues/1 first.

And also check out: https://community.home-assistant.io/t/home-assistant-add-on-postgresql-timescaledb/198176

This will point you into the right direction of using Timescale for long-running stats :)

When you want to connect to timescale form the outside world, you have to open-up it's ports in the configuration-page first:

![image](https://user-images.githubusercontent.com/26247804/201517815-f7d458e3-f7de-4113-8bf0-d6b8b248a199.png)

**Comment by eMerzh** [comment]
nice thanks :)

i can now connect , change the user & stuff 🎉 
still wondering where the data are, but now i'll  try to connect the recorder & ltss & stuff :)

**Comment by Expaso** [comment]
The recorder stores it's data in the events table, and ltss stores it in the ltss table.

From here, you can use all your query and timescale magic 🪄
