### ISSUE TITLE
Any plans for timescalesb 2.9, Postgres 14.6 and postgis 3.3.2

### ISSUE THREAD

**Issue by Delta1977** [Expaso/hassos-addon-timescaledb#29]
Any plans for timescalesb 2.9, Postgres 14.6 and postgis 3.3.2 ? 

Thank you for the good work👍

**Comment by Expaso** [comment]
Hi @Delta1977!

Thank you for your support!

I don't have any immediate plans, because recently I've bumped all versions to the latest available in November.

But you've made me curious now, what goodies are you looking for in these later versions?

**Comment by Expaso** [comment]
Ooofh... Postgis in Alpine 3.17 is already on PostgreSql 15!

This version-bumping is like domino! Once I'm trying to bump a version, it drags along a whole universe of packages.. 😖

**Comment by Expaso** [comment]
@Delta1977 haven't forgot you!

I'm trying to find a way to build all this stuff in, but my buildtimes are now over 6 hours, so Github just cancel my builds 😖
I have to split the whole thing up I suppose..

Quite an undertaking apparantly

**Comment by MrSpoocy** [comment]
Not sure if it can help, but GitHub support caching layer that can improve the build time. It scale my build time from 10min to < 1min. Eg. https://depot.dev/blog/docker-layer-caching-in-github-actions

**Comment by Expaso** [comment]
Still not forgotten.. I'm about to release an intermediate release very soon to pave the way to timescaledb-toolkit for the aarch64 and amd64 architechtures.

**Comment by Delta1977** [comment]
Thank you for release 3.0.0. 

It's so much faster than 2.1.1

Great work.

**Comment by Expaso** [comment]
Hi @Delta1977 !

And thank you so much for your support and patience! 🙏🏻
