### ISSUE TITLE
Recommandations on maintenance and backup

### ISSUE THREAD

**Issue by elfrinjo** [Expaso/hassos-addon-timescaledb#30]
Do you have any recommandationcs on regular maintenance Jobs like vacuum, analyze and reindex?

Also, what is the best way to perform regular database-dumps?
If I am not mistaken, pg-agent ist currently not able to do this because of https://github.com/Expaso/hassos-addon-pgadmin4/issues/6

**Comment by Expaso** [comment]
Hi @elfrinjo!

If al is well, vacuuming of the databases will happen automatically. See also: https://stackoverflow.com/questions/66469419/when-need-to-run-a-reindex-in-postgres

Postgresql will just auto-vacuum, and to the maintenance by itself.

For database-dumps, you can use use pg_dump using any scheduler you like (CRON, or Windows TaskScheduler). 
Though the mentioned bug report is about using pg_agent to dump the database in the /share folder of Home Assistant.
From there, you have to collect it to transfer it off your device, and in your backup for safety.

For now, you can just backup the addon using the home assistant backup. that works fine for regular backups.

**Comment by elfrinjo** [comment]
Thanks for your response! So I'll just leave the database alone :)

My plan for the backup would have been to
- schedule a job in pg_agent
- that creates a pg_dump in /share
- let ha backup take care of the contents of /share

However, if ha-backup covers the postgres-addon in a sensible manner I am happy with that!

**Comment by eMerzh** [comment]
Hello @Expaso , sorry to repost on this, but i'm looking at timescale backup and i'm not sure how it's done or not...
maybe you could add a small note in the readme or something?

I have Ltss and timescale and doing a pgdump of the timescale materialize view / continous aggregate doesn't really work , but you need to extract the data in csv or smth then reload it? 
how can i be sure that my views are well backed-up and that it contains data (that might not be in the ltss anymore)


thanks a lot for the work you do in this integration
