### ISSUE TITLE
Explain how to upgrade from 2.11 to 4.0 - and make it less precious!

### ISSUE THREAD

**Issue by mgg1010** [expaso/hassos-addon-timescaledb#44]
Hi

I tried upgrading from 2.11 to 4.0.   It upgraded, then I got an error saying "can't upgrade postgres 14, please update first" - and then the add-in shut down!  

I'm technical, but not a deep expert in HA - so I was lost.  I found instructions saying to upgrade PG I needed to use pgadmin - but I couldn't because the addin shut down.

I've managed to downgrade back to 2.11, so my setup is working.   But

1. Can you give me a route to upgrade?   Home Assistant doesn't support upgrading to 3.0, which might do it.   I might be able
to use portainer to do it, but any guidainces would be great

2. A thought for the future:  make it so the addin doesn't shut down so completely - or check for this condition sooner!

Thanks

Martin Green

**Comment by Expaso** [comment]
Hi Martin, do you still need some assistance with this?

**Comment by JeppeBoetkjaer** [comment]
I al also facing an issue going from 2.0.1 to 4.0.1

i just updated core and os and wanted to update all add-ons.

after this update no history was found, my enery dashboard is gone(maybe not related).

But also I cannot log into the database.

Tried downgrading using the backup but still no luck. Its been years since I set this up also the reason for the huge jump in versions.

I could do with any assistance maybe over Discord?

**Comment by Expaso** [comment]
Hi @JeppeBoetkjaer , sure I can try helping you out... Discord invite: https://discord.gg/JktdYKhE

**Comment by LaMiyu** [comment]
Unfortunately, I have the same problem.
I was never shown that there was an update of LTSS, with the last HA update there was now a note that the setup config is missing. After I added the source again the note:
 From 1.1.6 to 4.0.1

;(

Unfortunately the same problem, the update hangs with the note, cant upgrade postgres ...

Is there an "easy" way to export the database, delete LTSS completely, reinstall 4.0.1. and then just import the old data? ...

Even when importing a backup, my old data is back, but the recorder no longer works correctly and no new data (e.g. energy) is recorded ...
I would like to simply save the database with the backup and then set up LTSS completely new ... Is there a way to do this?

Thank you

**Comment by skank01** [comment]
Argh i got the same problem.
I'm on 4.0.1
Failed to start cause i need to upgrade.
My entire energy dashboard is gone.
How do i downgrade the addon and upgrade the db ?

**Comment by skank01** [comment]
> Hi
> 
> I tried upgrading from 2.11 to 4.0. It upgraded, then I got an error saying "can't upgrade postgres 14, please update first" - and then the add-in shut down!
> 
> I'm technical, but not a deep expert in HA - so I was lost. I found instructions saying to upgrade PG I needed to use pgadmin - but I couldn't because the addin shut down.
> 
> I've managed to downgrade back to 2.11, so my setup is working. But
> 
> 1. Can you give me a route to upgrade?   Home Assistant doesn't support upgrading to 3.0, which might do it.   I might be able
>    to use portainer to do it, but any guidainces would be great
> 2. A thought for the future:  make it so the addin doesn't shut down so completely - or check for this condition sooner!
> 
> Thanks
> 
> Martin Green

Hi, how did u downgrade the addon?

**Comment by skank01** [comment]
@Expaso can you help me please? Thx in advance

**Comment by LaMiyu** [comment]
> > Hi
> > I tried upgrading from 2.11 to 4.0. It upgraded, then I got an error saying "can't upgrade postgres 14, please update first" - and then the add-in shut down!
> > I'm technical, but not a deep expert in HA - so I was lost. I found instructions saying to upgrade PG I needed to use pgadmin - but I couldn't because the addin shut down.
> > I've managed to downgrade back to 2.11, so my setup is working. But
> > 
> > 1. Can you give me a route to upgrade?   Home Assistant doesn't support upgrading to 3.0, which might do it.   I might be able
> >    to use portainer to do it, but any guidainces would be great
> > 2. A thought for the future:  make it so the addin doesn't shut down so completely - or check for this condition sooner!
> > 
> > Thanks
> > Martin Green
> 
> Hi, how did u downgrade the addon?

Hello,

I was able to restore the backup of HA.
This was created automatically during the upgrade.
System -> Backup -> Select TimeScaleDB -> Restore

**Comment by skank01** [comment]
Hi
Good idea, will try that.
After reverting to old one, did you succeed in upgrading to new one too?

Op zo 23 jun. 2024 16:47 schreef LaMiyu ***@***.***>:

**Comment by skank01** [comment]
OK managed to revert back and all is working again. Can you explain me now how to properly update?

**Comment by mgg1010** [comment]
Expanso

Very, very sorry for the slow reply.   I appreciate your offer, and it's very useful - I'll connect on Discord.  The problem is that this is a home activity for me, and work is crazy...  

If there's a route where I can backup the DB, and install the newest version and then just copy the tables - maybe that's the best option?   I'm a developer by background, so very technical but not very experienced in this environment.

Thanks

Martin

**Comment by mgg1010** [comment]
Oops - discord invite expired too!

**Comment by skank01** [comment]
> > > Hi
> > > I tried upgrading from 2.11 to 4.0. It upgraded, then I got an error saying "can't upgrade postgres 14, please update first" - and then the add-in shut down!
> > > I'm technical, but not a deep expert in HA - so I was lost. I found instructions saying to upgrade PG I needed to use pgadmin - but I couldn't because the addin shut down.
> > > I've managed to downgrade back to 2.11, so my setup is working. But
> > > 
> > > 1. Can you give me a route to upgrade?   Home Assistant doesn't support upgrading to 3.0, which might do it.   I might be able
> > >    to use portainer to do it, but any guidainces would be great
> > > 2. A thought for the future:  make it so the addin doesn't shut down so completely - or check for this condition sooner!
> > > 
> > > Thanks
> > > Martin Green
> > 
> > 
> > Hi, how did u downgrade the addon?
> 
> Hello,
> 
> I was able to restore the backup of HA. This was created automatically during the upgrade. System -> Backup -> Select TimeScaleDB -> Restore

Hi , do you know how to properly update now?

**Comment by LaMiyu** [comment]
> > > > Hi
> > > > I tried upgrading from 2.11 to 4.0. It upgraded, then I got an error saying "can't upgrade postgres 14, please update first" - and then the add-in shut down!
> > > > I'm technical, but not a deep expert in HA - so I was lost. I found instructions saying to upgrade PG I needed to use pgadmin - but I couldn't because the addin shut down.
> > > > I've managed to downgrade back to 2.11, so my setup is working. But
> > > > 
> > > > 1. Can you give me a route to upgrade?   Home Assistant doesn't support upgrading to 3.0, which might do it.   I might be able
> > > >    to use portainer to do it, but any guidainces would be great
> > > > 2. A thought for the future:  make it so the addin doesn't shut down so completely - or check for this condition sooner!
> > > > 
> > > > Thanks
> > > > Martin Green
> > > 
> > > 
> > > Hi, how did u downgrade the addon?
> > 
> > 
> > Hello,
> > I was able to restore the backup of HA. This was created automatically during the upgrade. System -> Backup -> Select TimeScaleDB -> Restore
> 
> Hi , do you know how to properly update now?

i haven't find a solution until now ... i have a backup of my 1.1.6 timescale DB with all the Data and make some csv exports from pgadmin also a backup as sql from the database.
But i cannot import anything in the 4.x Version - At the moment i have no solution. ;( All my historical Data are lost ...

**Comment by skank01** [comment]
@Expaso how do we update from 2.0.1?

**Comment by skank01** [comment]
@Expaso is it possible to please reply?
We are stuck on how to update

**Comment by skank01** [comment]
> I al also facing an issue going from 2.0.1 to 4.0.1
> 
> i just updated core and os and wanted to update all add-ons.
> 
> after this update no history was found, my enery dashboard is gone(maybe not related).
> 
> But also I cannot log into the database.
> 
> Tried downgrading using the backup but still no luck. Its been years since I set this up also the reason for the huge jump in versions.
> 
> I could do with any assistance maybe over Discord?

Hi did you manage to upgrade correctly? Can you help me, cause @Expaso  isnt replying anymore and i cant update the addon cause of this problem

**Comment by Expaso** [comment]
Hi all! Back again! 

Sorry for the delay, I was on the other side of the world for a project for quite some time, so I did not had a change to look into this, but I'm currently testing a possibility.. 

Stay close, Im on it right now.

**Comment by Expaso** [comment]
I have found a way of upgrading the intermediate steps of the addon manually.

Here are the instructions:

1) Make sure you have a backup of your timescale addon!

2) Obtain SSH root access to your home-assistant installation, using this method: https://developers.home-assistant.io/docs/operating-system/debugging/

3) 

**Important!** Replace _aarch64_ with _amd64_ if you are on a x64 machine. If you are on a raspberry PI or other embedded board, mostly you'll have to use *aarch64*

### To upgrade from *1.x.x*, run the *2.1.1* version using this command:

`
docker run --rm --name timescaledb-upgrade -v /mnt/data/supervisor/addons/data/77b2833f_timescaledb/:/data:rw husselhans/hassos-addon-timescaledb-aarch64:2.1.1
`

### To upgrade from *2.x.x*, run the *3.0.1* version using this command:

`
docker run --rm --name timescaledb-upgrade -v /mnt/data/supervisor/addons/data/77b2833f_timescaledb/:/data:rw husselhans/hassos-addon-timescaledb-aarch64:3.0.1
`

### To upgrade from *3.x.x*, run the *4.0.1* version using this command:

`
docker run --rm --name timescaledb-upgrade -v /mnt/data/supervisor/addons/data/77b2833f_timescaledb/:/data:rw husselhans/hassos-addon-timescaledb-aarch64:4.0.1
`

From here, the normal home-assistant upgrade should be back on track again.

**Comment by Expaso** [comment]
> ion - At the moment i have no solution. ;( All my historical Data are lost ...

Probably your data is still there, as it's just moved to another folder internally.  Reach out on discord, so I can help you: https://discord.gg/wScb9jjr

**Comment by skank01** [comment]
> 5\. e Assistant. You should be good to go.

Hi,

No need to excuse yourself... You are doing this all in your free time.
Thx a lot for all your work, and keeping this alive.
Much appreciated !

I just tested your solution ,and i can confirm i could easily upgrade now from 2.0.1 to 4.0.1
All is working fine now, a big thanks !!!

**Comment by Expaso** [comment]
Great to hear!! 

And thank you for using the addon! Enjoy!!

**Comment by expaso** [comment]
@JeppeBoetkjaer @skank01 
Do you still need assistance?

**Comment by skank01** [comment]
No for me this is closed. I am enjoying it
