### ISSUE TITLE
 installation timescaledb failed in HA RPI4

### ISSUE THREAD

**Issue by todool** [expaso/hassos-addon-timescaledb#45]
I am not able to install timescaledb in raspberry Pi 4, see log. All other addons are working fine,

2024-05-14 08:17:43.508 INFO (MainThread) [supervisor.docker.interface] Downloading docker image husselhans/hassos-addon-timescaledb-aarch64 with tag 4.0.1.
2024-05-14 08:17:44.797 ERROR (MainThread) [supervisor.docker.interface] Can't install husselhans/hassos-addon-timescaledb-aarch64:4.0.1: 500 Server Error for http+docker://localhost/v1.44/images/husselhans/hassos-addon-timescaledb-aarch64:4.0.1/json: Internal Server Error ("layer does not exist")
HA:
Core
2024.5.3
Supervisor
2024.05.1

**Comment by Expaso** [comment]
Hi @todool , That almost looks like dockerhub screwed up...
Maybe it's a temporary issue on their side, but if you still have this issue, can I perhaps assist you trough discord?

Invite link: https://discord.gg/JktdYKhE

**Comment by ruben-s** [comment]
Hi,

I also tried to install Timescale DB.
The install failed with following message:

`Can't install husselhans/hassos-addon-timescaledb-amd64:4.0.1: 404 Client Error for http+docker://localhost/v1.45/images/husselhans/hassos-addon-timescaledb-amd64:4.0.1/json: Not Found ("No such image: husselhans/hassos-addon-timescaledb-amd64:4.0.1")`

What supprises me is that it seems to try to download the docker image from localhost.
It should go to docker hub?
Can you point me to the location of the config for this, then I can try to alter it to point to docker hub.

This is on
Home Assistant Supervised 24.3.3 installed on a intel pc on debian 12.

Thx for your feed-back.

br,
 Ruben

**Comment by Expaso** [comment]
Hi @ruben-s , 

Sorry for the late reply.
I have no config file with that specific path.. It's like homeassistant or your local docker config makes that up by itself for some reason..?

The actual images for your platform are here: https://hub.docker.com/repository/docker/husselhans/hassos-addon-timescaledb-amd64/general

Are you actually still experience this issue?

**Comment by expaso** [comment]
Hi Ruben , 

I cannot control the error message. It's not the addon that does this, it's the supervisor of HA.
Thank for replying! I will close the issue. Glad the fix was easy for my part ;)
