### ISSUE TITLE
pg_hba.conf - In which directory of HA

### ISSUE THREAD

**Issue by GG29071974** [expaso/hassos-addon-timescaledb#49]
Hi together,

i installed succesfull timescaledb and pgadmin on my Homeassistant NUC.
I even installed the filebrowser to make some configs.
For postgreSQL that I can admin it with pgadmin I have to edit the pg_hba.conf
=> 127.0.0.1/32
Localhost for edit with pgadmin over port 5432.
At the moment it is not possible because in pg_hba.conf is 0.0.0.0/32 is written
So my problem as "beginner for postgreSQL and HA" is:
Where is the pg_hba.conf file ? In description of your timescale there is only said, that it is in "data"
In the mein data directory I dont find something...
Can you tell me the path of directory for pg_hba.conf.

Thank you very much.

Regards
Gunter

**Comment by GG29071974** [comment]
Hi Expasio

Thanks for the very usefull support !

Last questioms:  

1.)  There I have two packages of you in your repository
 pgAdmin and TimescalaDB
If I install pgAdmin then everything is already installed even your tool ?
I can reach your addon then ? Or where I see this addon ?
 Regards
Gunter

**Comment by GG29071974** [comment]
ok fine everything works !
If I use local on homeassistant the hostname '77b2833f-timescaledb' in pgAdmin I can use and configure everything in postgreSQL DB.
But if I want to access to postgresql DB from external client in network...
What is the best way to configure  ? At the moment connection will be refused ..

THX
Regards
Gunter

**Comment by expaso** [comment]
> But if I want to access to postgresql DB from external client in network... What is the best way to configure ? At the moment connection will be refused ..

Thats in my first reply, you should open-up the postresql port:

![image](https://github.com/user-attachments/assets/da4c0493-b224-43b2-8e69-52789c428bd7)
