### ISSUE TITLE
Create index on (entity_id, time)

### ISSUE THREAD

**Issue by sithmein** [Expaso/hassos-addon-timescaledb#6]
Currently the TimescaleDB extension creates two indexes, on on entity_id and one on time. However, most queries will filter by both entity and time and therefore a compound index on both (entity_id, time DESC) will improve those queries considerably. The TimescaleDB manual also suggests creating such indexes.

**Comment by Expaso** [comment]
Hi @sithmein , Is this issue still relevant?

**Comment by sithmein** [comment]
No. It has already been implemented in the HA ltss add-on. I tend to confuse HA add-ons with hassos add-ons.
